// Cambridge IGCSE (9-1) subjects
// 9-1 grading scale — newer Cambridge qualifications

export const IGCSE91_SUBJECTS = [
  {
    code: '0610',
    code91: '0970',
    name: 'Biology',
    color: 'emerald',
    icon: '',
    description: 'Cell Biology, Genetics, Ecology, Human Biology',
  },
  {
    code: '0620',
    code91: '0971',
    name: 'Chemistry',
    color: 'green',
    icon: '',
    description: 'Atomic Structure, Reactions, Organic Chemistry',
  },
  {
    code: '0625',
    code91: '0972',
    name: 'Physics',
    color: 'purple',
    icon: '',
    description: 'Forces, Waves, Electricity, Nuclear Physics',
  },
  {
    code: '0580',
    code91: '0980',
    name: 'Mathematics',
    color: 'blue',
    icon: '',
    description: 'Number, Algebra, Geometry, Statistics, Probability',
  },
  {
    code: '0606',
    code91: '0980',
    name: 'Additional Mathematics',
    color: 'indigo',
    icon: '',
    description: 'Advanced Algebra, Calculus, Trigonometry',
  },
  {
    code: '0478',
    code91: '0984',
    name: 'Computer Science',
    color: 'cyan',
    icon: '',
    description: 'Theory, Algorithms, Programming, Databases',
  },
  {
    code: '0455',
    code91: '0987',
    name: 'Economics',
    color: 'yellow',
    icon: '',
    description: 'Micro & Macroeconomics, International Trade',
  },
  {
    code: '0450',
    code91: '0986',
    name: 'Business Studies',
    color: 'orange',
    icon: '',
    description: 'Marketing, Finance, Operations, Management',
  },
  {
    code: '0452',
    code91: '0985',
    name: 'Accounting',
    color: 'amber',
    icon: '',
    description: 'Financial Statements, Bookkeeping, Costing',
  },
  {
    code: '0470',
    code91: '0977',
    name: 'History',
    color: 'red',
    icon: '',
    description: 'Modern World History, Historical Sources',
  },
  {
    code: '0460',
    code91: '0976',
    name: 'Geography',
    color: 'teal',
    icon: '',
    description: 'Physical and Human Geography, Fieldwork',
  },
  {
    code: '0500',
    code91: '0990',
    name: 'English — First Language',
    color: 'stone',
    icon: '',
    description: 'Reading, Writing, Creative & Directed Writing',
  },
  {
    code: '0475',
    code91: '0992',
    name: 'English Literature',
    color: 'rose',
    icon: '',
    description: 'Poetry, Prose, Drama — set texts',
  },
  {
    code: '0447',
    code91: '0973',
    name: 'Co-ordinated Sciences',
    color: 'lime',
    icon: '',
    description: 'Combined Biology, Chemistry and Physics',
  },
] as const;

export type IGCSE91SubjectCode = typeof IGCSE91_SUBJECTS[number]['code91'];
