// Cambridge O Level subjects

export const OLEVEL_SUBJECTS = [
  {
    code: '5090',
    name: 'Biology',
    color: 'emerald',
    icon: '',
    description: 'Cell Biology, Genetics, Ecology, Human Biology',
  },
  {
    code: '5070',
    name: 'Chemistry',
    color: 'green',
    icon: '',
    description: 'Atomic Structure, Reactions, Organic Chemistry',
  },
  {
    code: '5054',
    name: 'Physics',
    color: 'purple',
    icon: '',
    description: 'Forces, Waves, Electricity, Nuclear Physics',
  },
  {
    code: '4024',
    name: 'Mathematics D',
    color: 'blue',
    icon: '',
    description: 'Number, Algebra, Geometry, Statistics',
  },
  {
    code: '4037',
    name: 'Additional Mathematics',
    color: 'indigo',
    icon: '',
    description: 'Advanced Algebra, Calculus, Trigonometry',
  },
  {
    code: '2210',
    name: 'Computer Science',
    color: 'cyan',
    icon: '',
    description: 'Theory, Algorithms, Programming, Databases',
  },
  {
    code: '2281',
    name: 'Economics',
    color: 'yellow',
    icon: '',
    description: 'Micro & Macroeconomics, International Trade',
  },
  {
    code: '7115',
    name: 'Business Studies',
    color: 'orange',
    icon: '',
    description: 'Marketing, Finance, Operations, Management',
  },
  {
    code: '7110',
    name: 'Principles of Accounts',
    color: 'amber',
    icon: '',
    description: 'Financial Accounts, Bookkeeping, Analysis',
  },
  {
    code: '1123',
    name: 'English Language',
    color: 'stone',
    icon: '',
    description: 'Reading, Writing, Comprehension',
  },
  {
    code: '2059',
    name: 'Pakistan Studies',
    color: 'teal',
    icon: '',
    description: 'History, Geography and Culture of Pakistan',
  },
  {
    code: '4040',
    name: 'Statistics',
    color: 'violet',
    icon: '',
    description: 'Data Collection, Probability, Statistical Methods',
  },
  {
    code: '7100',
    name: 'Commerce',
    color: 'rose',
    icon: '',
    description: 'Trade, Finance, Transport, Insurance',
  },
  {
    code: '7707',
    name: 'Accounting',
    color: 'lime',
    icon: '',
    description: 'Financial Statements, Bookkeeping, Costing',
  },
  {
    code: '7010',
    name: 'Computer Studies',
    color: 'sky',
    icon: '',
    description: 'Hardware, Software, Programming Concepts',
  },
  {
    code: '3204',
    name: 'Bengali',
    color: 'red',
    icon: '',
    description: 'Bengali Language and Literature',
  },
  {
    code: '7094',
    name: 'Bangladesh Studies',
    color: 'slate',
    icon: '',
    description: 'History, Geography and Culture of Bangladesh',
  },
] as const;

export type OLevelSubjectCode = typeof OLEVEL_SUBJECTS[number]['code'];
